apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-xssl
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/happy-path-service-tenant/appstudio/dc-metro-map-xssl@sha256:96f1d0c323da1e57666999d3f1b635eccb9b5467453e62ac201a8019bc07c858
        name: my-nodejs
        resources: {}
status: {}
